# Use root/example as user/password credentials

services:

  db:
    image: mysql:9.5.0-oracle
    container_name: mysql
    ports: 
      - 3306:3306
    environment:
      MYSQL_USER: gvendas
      MYSQL_PASSWORD: gvendas
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gvendas_db
    # (this is just an example, not intended to be a production configuration)
